name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: install, build
        run: |
          yarn install
          yarn build
      - name: test
        run: yarn test
