name: Node CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: install, build
        run: |
          yarn install
          yarn build
      - name: test
        run: yarn test
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./artifacts/test-result-junit.xml
