name: Publish
on:
  create:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install, build
        run: |
          yarn install
          yarn build
      - name: test
        run: yarn test
      - name: publish
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: 'publish --access public'
